"""
Domain Expert Template System

This module provides templates and utilities for easily creating new domain experts,
making it scalable to handle hundreds of biological techniques.
"""

from pathlib import Path
from typing import Dict, List, Optional, Any
import json
from dataclasses import asdict

from .core import (
    DomainExpert, DomainPrompt, TechniqueMetadata, 
    ExpertiseLevel, BiologicalContext, BaseDomainExpert
)


class DomainExpertTemplate:
    """Template for creating new domain experts"""
    
    @staticmethod
    def create_basic_expert(
        technique_name: str,
        display_name: str,
        description: str,
        category: str,
        subcategory: Optional[str] = None,
        aliases: Optional[List[str]] = None,
        expertise_level: ExpertiseLevel = ExpertiseLevel.INTERMEDIATE
    ) -> BaseDomainExpert:
        """Create a basic domain expert with minimal prompts"""
        
        metadata = TechniqueMetadata(
            name=technique_name.lower().replace(" ", "_").replace("-", "_"),
            display_name=display_name,
            description=description,
            category=category,
            subcategory=subcategory,
            aliases=aliases or [],
            required_expertise=expertise_level,
            version="1.0"
        )
        
        expert = BaseDomainExpert(metadata)
        
        # Add basic interpretation prompt
        basic_prompt = DomainPrompt(
            name="basic_interpretation",
            description=f"Basic interpretation for {display_name} results",
            template=f"""
Based on the {display_name} analysis results:

- Analysis type: {technique_name}
- Key findings: {{key_findings}}
- Statistical significance: {{significance}}
- Sample information: {{sample_info}}

Please provide an interpretation of these results, including:
1. Biological significance of the findings
2. Potential implications for the research question
3. Suggested follow-up analyses or experiments
4. Any limitations or caveats to consider
""",
            parameters=["key_findings", "significance", "sample_info"],
            expertise_level=expertise_level,
            biological_context=BiologicalContext.GENE_EXPRESSION,
            tags={"basic", "interpretation"}
        )
        
        expert.add_prompt(basic_prompt)
        return expert
    
    @staticmethod
    def generate_expert_module_code(
        technique_name: str,
        display_name: str,
        description: str,
        category: str,
        prompts_config: List[Dict[str, Any]],
        subcategory: Optional[str] = None,
        aliases: Optional[List[str]] = None,
        expertise_level: ExpertiseLevel = ExpertiseLevel.INTERMEDIATE
    ) -> str:
        """Generate Python code for a new domain expert module"""
        
        class_name = f"{technique_name.replace('_', '').replace('-', '').title()}DomainExpert"
        
        # Generate imports
        imports = '''"""
{display_name} Domain Expert

This module provides domain expertise for {description}.
"""

from typing import Dict
from ..core import (
    DomainExpert, DomainPrompt, TechniqueMetadata, 
    ExpertiseLevel, BiologicalContext
)
from ..registry import register_expert


'''.format(display_name=display_name, description=description.lower())
        
        # Generate class definition
        class_def = f'''class {class_name}(DomainExpert):
    """Domain expert for {display_name} analysis"""
    
    def get_metadata(self) -> TechniqueMetadata:
        return TechniqueMetadata(
            name="{technique_name}",
            display_name="{display_name}",
            description="{description}",
            category="{category}",
            subcategory={f'"{subcategory}"' if subcategory else 'None'},
            aliases={aliases or []},
            related_techniques=[],  # TODO: Add related techniques
            typical_applications=[
                # TODO: Add typical applications
            ],
            required_expertise=ExpertiseLevel.{expertise_level.name},
            version="1.0",
            author="Generated by Template System"
        )
    
    def get_prompts(self) -> Dict[str, DomainPrompt]:
        """Get all {display_name} domain prompts"""
        return {{
'''
        
        # Generate prompts
        prompts_code = ""
        for i, prompt_config in enumerate(prompts_config):
            prompt_name = prompt_config["name"]
            prompt_desc = prompt_config["description"]
            prompt_template = prompt_config["template"]
            prompt_params = prompt_config["parameters"]
            prompt_context = prompt_config.get("biological_context", "GENE_EXPRESSION")
            prompt_expertise = prompt_config.get("expertise_level", expertise_level.name)
            prompt_tags = prompt_config.get("tags", ["generated"])
            
            prompts_code += f'''            "{prompt_name}": DomainPrompt(
                name="{prompt_name}",
                description="{prompt_desc}",
                template="""{prompt_template}""",
                parameters={prompt_params},
                expertise_level=ExpertiseLevel.{prompt_expertise},
                biological_context=BiologicalContext.{prompt_context},
                tags={set(prompt_tags)}
            )'''
            
            if i < len(prompts_config) - 1:
                prompts_code += ",\n"
        
        class_def += prompts_code + '''
        }


'''
        
        # Generate registration and main
        registration = f'''# Auto-register this expert when module is imported
register_expert({class_name})


if __name__ == "__main__":
    # Test the {display_name} expert
    print("Testing {display_name} Domain Expert")
    
    expert = {class_name}()
    metadata = expert.get_metadata()
    
    print(f"Expert: {{metadata.display_name}}")
    print(f"Category: {{metadata.category}}")
    
    prompts = expert.get_prompts()
    print(f"Total prompts: {{len(prompts)}}")
    
    # Validation
    errors = expert.validate_prompts()
    print(f"Validation errors: {{len(errors)}}")
    if errors:
        for error in errors:
            print(f"  - {{error}}")
'''
        
        return imports + class_def + registration
    
    @staticmethod
    def create_expert_from_config(config_path: Path) -> str:
        """Create a domain expert from a JSON configuration file"""
        with open(config_path) as f:
            config = json.load(f)
        
        return DomainExpertTemplate.generate_expert_module_code(
            technique_name=config["technique_name"],
            display_name=config["display_name"],
            description=config["description"],
            category=config["category"],
            prompts_config=config["prompts"],
            subcategory=config.get("subcategory"),
            aliases=config.get("aliases", []),
            expertise_level=ExpertiseLevel(config.get("expertise_level", "INTERMEDIATE"))
        )
    
    @staticmethod
    def generate_config_template(technique_name: str, output_path: Path):
        """Generate a configuration template for a new technique"""
        template_config = {
            "technique_name": technique_name.lower().replace(" ", "_").replace("-", "_"),
            "display_name": technique_name,
            "description": f"Analysis technique for {technique_name.lower()}",
            "category": "TODO: Add category (e.g., Transcriptomics, Genomics, Proteomics)",
            "subcategory": None,
            "aliases": [],
            "expertise_level": "INTERMEDIATE",
            "prompts": [
                {
                    "name": "interpret_results",
                    "description": f"Interpret {technique_name} analysis results",
                    "template": f"""
Based on the {technique_name} analysis results:

- Key metric 1: {{metric1}}
- Key metric 2: {{metric2}}
- Statistical significance: {{significance}}

Please provide an interpretation, including:
1. Biological significance of the results
2. Implications for the research question
3. Suggested follow-up analyses
""",
                    "parameters": ["metric1", "metric2", "significance"],
                    "biological_context": "GENE_EXPRESSION",
                    "expertise_level": "INTERMEDIATE",
                    "tags": ["interpretation", "results"]
                },
                {
                    "name": "troubleshoot_analysis",
                    "description": f"Help troubleshoot {technique_name} analysis issues",
                    "template": f"""
{technique_name} analysis issue:

- Problem description: {{problem_description}}
- Error message: {{error_message}}
- Analysis parameters: {{parameters}}

Please provide troubleshooting guidance:
1. Likely causes of the issue
2. Solutions to try
3. Parameter adjustments
""",
                    "parameters": ["problem_description", "error_message", "parameters"],
                    "biological_context": "TROUBLESHOOTING",
                    "expertise_level": "EXPERT",
                    "tags": ["troubleshooting", "debugging"]
                }
            ]
        }
        
        with open(output_path, 'w') as f:
            json.dump(template_config, f, indent=2)
        
        return template_config


class TechniqueGenerator:
    """Generator for creating multiple techniques from templates"""
    
    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_from_list(self, techniques: List[Dict[str, Any]]):
        """Generate multiple domain experts from a list of technique configurations"""
        generated_files = []
        
        for technique_config in techniques:
            filename = f"{technique_config['technique_name']}.py"
            output_path = self.output_dir / filename
            
            # Generate the module code
            module_code = DomainExpertTemplate.generate_expert_module_code(
                **technique_config
            )
            
            # Write to file
            with open(output_path, 'w') as f:
                f.write(module_code)
            
            generated_files.append(output_path)
        
        return generated_files
    
    def generate_batch_configs(self, technique_names: List[str], configs_dir: Path):
        """Generate configuration templates for multiple techniques"""
        configs_dir.mkdir(parents=True, exist_ok=True)
        generated_configs = []
        
        for technique_name in technique_names:
            config_filename = f"{technique_name.lower().replace(' ', '_')}_config.json"
            config_path = configs_dir / config_filename
            
            DomainExpertTemplate.generate_config_template(technique_name, config_path)
            generated_configs.append(config_path)
        
        return generated_configs


# Predefined technique templates for common biological techniques
COMMON_TECHNIQUES = [
    {
        "technique_name": "chip_seq",
        "display_name": "ChIP-seq",
        "description": "Chromatin immunoprecipitation followed by sequencing",
        "category": "Epigenomics",
        "aliases": ["chip-seq", "chromatin-ip"],
        "expertise_level": ExpertiseLevel.EXPERT,
        "prompts_config": [
            {
                "name": "interpret_peaks",
                "description": "Interpret ChIP-seq peak calling results",
                "template": """
ChIP-seq peak analysis results:

- Total peaks identified: {total_peaks}
- Peak distribution: {peak_distribution}
- Top enriched regions: {top_regions}
- Motif analysis: {motif_results}

Please interpret these ChIP-seq results, including:
1. Quality of the ChIP-seq experiment
2. Biological significance of peak locations
3. Potential target genes and regulatory networks
4. Validation experiments to consider
""",
                "parameters": ["total_peaks", "peak_distribution", "top_regions", "motif_results"],
                "biological_context": "CHROMATIN_ACCESSIBILITY",
                "expertise_level": "EXPERT",
                "tags": ["peaks", "chromatin", "transcription-factors"]
            }
        ]
    },
    {
        "technique_name": "proteomics",
        "display_name": "Proteomics",
        "description": "Large-scale study of proteins and their modifications",
        "category": "Proteomics",
        "aliases": ["mass-spec", "protein-analysis"],
        "expertise_level": ExpertiseLevel.EXPERT,
        "prompts_config": [
            {
                "name": "interpret_protein_changes",
                "description": "Interpret differential protein expression results",
                "template": """
Proteomics analysis results:

- Proteins identified: {proteins_identified}
- Significantly changed proteins: {changed_proteins}
- Top upregulated: {top_upregulated}
- Top downregulated: {top_downregulated}
- Pathway analysis: {pathway_results}

Please interpret these proteomics results, including:
1. Biological significance of protein changes
2. Correlation with transcriptomic data if available
3. Potential biomarkers identified
4. Functional implications of the findings
""",
                "parameters": ["proteins_identified", "changed_proteins", "top_upregulated", 
                              "top_downregulated", "pathway_results"],
                "biological_context": "PROTEIN_ANALYSIS",
                "expertise_level": "EXPERT",
                "tags": ["proteins", "differential-expression", "biomarkers"]
            }
        ]
    }
]


if __name__ == "__main__":
    # Example usage of the template system
    print("Testing Domain Expert Template System")
    
    # Create a basic expert
    basic_expert = DomainExpertTemplate.create_basic_expert(
        technique_name="example_technique",
        display_name="Example Technique",
        description="An example biological technique for demonstration",
        category="Testing"
    )
    
    print(f"Created basic expert: {basic_expert.get_technique_name()}")
    print(f"Prompts: {list(basic_expert.get_prompts().keys())}")
    
    # Generate module code for ChIP-seq
    chipseq_config = COMMON_TECHNIQUES[0]
    chipseq_code = DomainExpertTemplate.generate_expert_module_code(
        **chipseq_config
    )
    
    print(f"\nGenerated ChIP-seq module code ({len(chipseq_code)} characters)")
    
    # Test configuration template generation
    config_path = Path("test_config.json")
    config = DomainExpertTemplate.generate_config_template("Test Technique", config_path)
    print(f"Generated config template: {config_path}")
    
    # Cleanup
    if config_path.exists():
        config_path.unlink()
    
    print("Template system test completed successfully!") 