name: ra
channels:
  - conda-forge
  - pytorch
  - fastai
  - bioconda
  - defaults
dependencies:
  - python=3.10 # or your preferred version
  - opencv
  - numpy
  - matplotlib
  - scipy
  - scikit-image
  - scikit-learn
  - pandas
  - pillow
  - gradio==4.44.1
  - streamlit
  - PyPDF2
  - biopython
  - requests
  - seaborn
  - PyYAML
  
  - pip
  - pip:
      - readlif
      - openai==1.77.0
      - joblib
      - streamlit-drawable-canvas
      - boto3
      - botocore
      - azure-identity
      - azure-mgmt-resource
      - spacy 
      - mcp
      - fastapi
      - uvicorn
      - pydantic
      - httpx
      - websockets
      - aiofiles
      - python-dotenv
      - asyncio-mqtt
      - jsonschema
      - plotly-express
      - scanpy
      

      