"""Differential abundance statistics.

These tests are the guard against the class of defect that made the old
proteomics and ATAC-seq servers scientifically useless: results that looked
plausible but were generated by `np.random`.
"""

import numpy as np
import pandas as pd
import pytest

from gliaent.analysis import AnalysisParams, adjust_pvalues, differential_expression
from gliaent.analysis.params import MultipleTestingMethod


class TestAdjustPvalues:
    def test_benjamini_hochberg_matches_statsmodels(self):
        from statsmodels.stats.multitest import multipletests

        raw = [0.001, 0.008, 0.039, 0.041, 0.042, 0.06, 0.074, 0.205]
        expected = multipletests(raw, method="fdr_bh")[1]
        np.testing.assert_allclose(adjust_pvalues(raw), expected)

    def test_adjusted_never_below_raw(self):
        raw = np.linspace(0.001, 0.9, 50)
        assert np.all(adjust_pvalues(raw) >= raw - 1e-12)

    def test_nan_stays_nan_and_is_excluded_from_correction(self):
        # The key property: an untestable feature must not count toward the
        # denominator, which would make every other feature look better.
        with_nan = adjust_pvalues([0.01, np.nan, 0.02, np.nan])
        without_nan = adjust_pvalues([0.01, 0.02])
        assert np.isnan(with_nan[1]) and np.isnan(with_nan[3])
        np.testing.assert_allclose(with_nan[[0, 2]], without_nan)

    def test_all_nan_returns_all_nan(self):
        assert np.all(np.isnan(adjust_pvalues([np.nan, np.nan])))

    def test_none_method_is_a_passthrough(self):
        raw = [0.01, 0.02, 0.03]
        np.testing.assert_allclose(
            adjust_pvalues(raw, MultipleTestingMethod.NONE), raw
        )

    def test_bonferroni_scales_by_n(self):
        assert adjust_pvalues(
            [0.01, 0.01], MultipleTestingMethod.BONFERRONI
        ).tolist() == pytest.approx([0.02, 0.02])


class TestDifferentialExpression:
    def test_null_data_yields_essentially_no_hits(self, null_dataset):
        """The test the fabricated implementation could never pass.

        With no real effect and FDR control at 0.05, significant calls should
        be rare. The old code returned ~100+ "significant proteins" here.
        """
        data, metadata = null_dataset
        result = differential_expression(data, metadata, "condition")
        assert result.n_significant <= 2, (
            f"{result.n_significant} false positives in null data; "
            "FDR control is not working"
        )

    def test_recovers_a_real_spiked_effect(self, spiked_dataset):
        data, metadata, spiked = spiked_dataset
        result = differential_expression(data, metadata, "condition")
        called = set(result.table.loc[result.table["significant"], "feature"])
        # All 20 genuinely-changed features should be found...
        assert set(spiked).issubset(called)
        # ...and essentially nothing else.
        assert len(called - set(spiked)) <= 2

    def test_spiked_direction_is_up(self, spiked_dataset):
        data, metadata, spiked = spiked_dataset
        result = differential_expression(data, metadata, "condition")
        regulation = result.table.set_index("feature").loc[spiked, "regulation"]
        assert (regulation == "up").all()

    def test_log2_fold_change_is_accurate(self):
        # A clean 4x increase must read as log2FC == 2.
        samples = ["a1", "a2", "a3", "b1", "b2", "b3"]
        data = pd.DataFrame(
            [[10.0, 10.0, 10.0, 40.0, 40.0, 40.0]], index=["P1"], columns=samples
        )
        metadata = pd.DataFrame({"g": ["ctl"] * 3 + ["trt"] * 3}, index=samples)
        result = differential_expression(data, metadata, "g")
        assert result.table.loc[0, "log2_fold_change"] == pytest.approx(2.0)

    def test_significant_and_regulation_never_disagree(self, spiked_dataset):
        """Guards the dea_plots.py bug where a feature could be
        category=='Significant' while significant==False."""
        data, metadata, _ = spiked_dataset
        table = differential_expression(data, metadata, "condition").table
        assert not (
            (table["regulation"] != "unchanged") & ~table["significant"]
        ).any()
        assert not (
            table["significant"] & (table["regulation"] == "unchanged")
        ).any()

    def test_significance_uses_adjusted_not_raw_pvalues(self, null_dataset):
        data, metadata = null_dataset
        result = differential_expression(data, metadata, "condition")
        sig = result.table[result.table["significant"]]
        assert (sig["p_value_adjusted"] < 0.05).all()

    def test_underpowered_features_get_nan_not_a_made_up_pvalue(self):
        """The `else [0.01] * n_genes` bug: never invent a p-value."""
        samples = ["a1", "b1"]  # 1 per group, below min_count
        data = pd.DataFrame([[1.0, 5.0]], index=["P1"], columns=samples)
        metadata = pd.DataFrame({"g": ["ctl", "trt"]}, index=samples)
        result = differential_expression(data, metadata, "g")
        assert np.isnan(result.table.loc[0, "p_value"])
        assert not result.table.loc[0, "significant"]
        assert result.n_skipped == 1
        assert result.n_tested == 0

    def test_zero_variance_feature_is_not_significant(self):
        samples = [f"a{i}" for i in range(4)] + [f"b{i}" for i in range(4)]
        data = pd.DataFrame([[7.0] * 8], index=["P1"], columns=samples)
        metadata = pd.DataFrame({"g": ["ctl"] * 4 + ["trt"] * 4}, index=samples)
        result = differential_expression(data, metadata, "g")
        assert not result.table.loc[0, "significant"]

    def test_nan_values_are_tolerated(self):
        rng = np.random.default_rng(3)
        samples = [f"a{i}" for i in range(5)] + [f"b{i}" for i in range(5)]
        values = rng.normal(10, 1, size=(10, 10))
        values[0, 0] = np.nan
        data = pd.DataFrame(values, index=[f"P{i}" for i in range(10)], columns=samples)
        metadata = pd.DataFrame({"g": ["ctl"] * 5 + ["trt"] * 5}, index=samples)
        result = differential_expression(data, metadata, "g")
        assert len(result.table) == 10

    def test_zero_mean_does_not_produce_infinite_fold_change(self):
        samples = [f"a{i}" for i in range(3)] + [f"b{i}" for i in range(3)]
        data = pd.DataFrame(
            [[0.0, 0.0, 0.0, 5.0, 5.0, 5.0]], index=["P1"], columns=samples
        )
        metadata = pd.DataFrame({"g": ["ctl"] * 3 + ["trt"] * 3}, index=samples)
        result = differential_expression(data, metadata, "g")
        assert np.isfinite(result.table.loc[0, "log2_fold_change"])

    def test_summary_carries_the_params_that_produced_it(self, spiked_dataset):
        data, metadata, _ = spiked_dataset
        params = AnalysisParams(alpha=0.01, log2fc_threshold=0.5, seed=42)
        summary = differential_expression(
            data, metadata, "condition", params=params
        ).summary()
        assert summary["params"]["alpha"] == 0.01
        assert summary["params"]["seed"] == 42
        assert "fdr_bh" in summary["significance_criterion"]

    def test_stricter_alpha_cannot_increase_hits(self, spiked_dataset):
        data, metadata, _ = spiked_dataset
        lenient = differential_expression(
            data, metadata, "condition", params=AnalysisParams(alpha=0.05)
        ).n_significant
        strict = differential_expression(
            data, metadata, "condition", params=AnalysisParams(alpha=0.001)
        ).n_significant
        assert strict <= lenient

    def test_mannwhitney_also_controls_false_positives(self, null_dataset):
        data, metadata = null_dataset
        result = differential_expression(
            data, metadata, "condition", test="mannwhitney"
        )
        assert result.n_significant <= 2


class TestDifferentialExpressionErrors:
    """Errors must be raised, not swallowed into a success payload."""

    def test_missing_group_column_raises(self, null_dataset):
        data, metadata = null_dataset
        with pytest.raises(ValueError, match="group column"):
            differential_expression(data, metadata, "nonexistent")

    def test_transposed_input_raises_with_a_useful_message(self, null_dataset):
        data, metadata = null_dataset
        with pytest.raises(ValueError, match="features x samples"):
            differential_expression(data.T, metadata, "condition")

    def test_single_group_raises(self):
        samples = ["a1", "a2", "a3"]
        data = pd.DataFrame([[1.0, 2.0, 3.0]], index=["P1"], columns=samples)
        metadata = pd.DataFrame({"g": ["ctl"] * 3}, index=samples)
        with pytest.raises(ValueError, match="at least 2 groups"):
            differential_expression(data, metadata, "g")

    def test_unknown_group_name_raises(self, null_dataset):
        data, metadata = null_dataset
        with pytest.raises(ValueError, match="not found"):
            differential_expression(
                data, metadata, "condition", group_b="does_not_exist"
            )

    def test_unknown_test_raises(self, null_dataset):
        data, metadata = null_dataset
        with pytest.raises(ValueError, match="unknown test"):
            differential_expression(data, metadata, "condition", test="bogus")
